default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: "12345678"
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: notebook_study_design_development

test:
  <<: *default
  database: notebook_study_design_test

production:
  <<: *default
  database: notebook_study_design_production
  username: notebook_study_design
  password: <%= ENV['NOTEBOOK_STUDY_DESIGN_DATABASE_PASSWORD'] %>
